services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - qdrant
    environment:
      QDRANT_URL: http://qdrant:6333
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GPTUNNEL_API_KEY: ${GPTUNNEL_API_KEY}

configs:
  qdrant_config:
    content: |
      log_level: INFO
